name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Install yarn
        run: npm install -g yarn
      - name: Install deps
        run: yarn install
      - name: Run Prettier
        run: yarn check-prettier
      - name: Run Tests
        run: yarn ci-test
